name: hello_world
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: echo "Hello World "
        run: echo ${TOKEN}
