name: hello_world
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        env:
          TOKEN: ${{ secrets.VSCE }}
        run: |
          echo "Hello World "
          echo ${TOKEN}
